### ISSUE TITLE
Validace projects

### ISSUE THREAD

**Issue by MichalBryxi** [MichalBryxi/bludistak#22]
Přidej validace na jednotlivé položky modelu projects tak, aby:

- [x] jméno muselo být vyplněno: http://stackoverflow.com/questions/15482354/how-to-validate-text-isnt-blank-in-rails
- [x] description nemusí být vyplněno
- [x] zajisti, aby "active" zaškrtávátko ve formuláři bylo defaultně zaškrtnuto. To se dá udělat tak, že napíšeš migraci, která řekne databázi, že daný sloupec má výchozí hodnotu na "true" a to pak budou railsy při generování respektovat: http://stackoverflow.com/questions/4116415/preselect-check-box-with-rails-simple-form
- [x] name, description, active nesmí být null: http://stackoverflow.com/questions/5966840/how-to-change-a-nullable-column-to-not-nullable-in-a-rails-migration

**Comment by maniac1234** [comment]
hotovo
