### ISSUE TITLE
pages

### ISSUE THREAD

**Issue by MichalBryxi** [MichalBryxi/bludistak#38]
- [x] vytvorit statickou stranku pages/about
 - [x] kontakt na autory (my tri)
 - [x] kontakt na DDD
 - [x] zakladni popis o cem projekt je
 - [x] polozka "co" ukazuje na "new worm" - to je ok, ale dal bych tomu popisek "udelit bludistaka"
- [x] vytvorit statickou stranku pages/home
 - [x] Hezky, strucne popsat projekt
 - [x] Navnadit lidi, aby se registrovali

**Comment by MichalBryxi** [comment]
Základní popis: 

Cílem projektu je přiblížit vývoj webové aplikace za použití technologií jako je Ruby on Rails, HTML, CSS, Bootstrap from Twitter, Heroku, Nitrous.io úplným začátečníkům. Nepředpokládá se předchozí znalost žádné z těchto technologií.

S tímto účelem byla vytvořena aplikace bludišťák, která umožňuje přihlášenému uživateli "dát bludišťáka" a tím ohodnotit jiného uživatele.

**Comment by MichalBryxi** [comment]
Home:

Začni hned!
Vstup do aplikace je zdarma. Stačí se přihlásit přes [fb ikonka], nebo [twitter ikonka]

**Comment by MichalBryxi** [comment]
Home:

Blidišťákuj! <--- překlep
Naštval tě někdo? Udělal ti radost? Chceš ho prostě patřičně ohodnotit? Prostě mu [dej bludiťáka] - odkaz na přidání bludišťáka

**Comment by MichalBryxi** [comment]
Home:

Rozdej je všechny => To je super :) 

Přidal bych různé tématické ikonky a pod ně příslušné nápisy:

 1. Jsi super!
 2. Tohle mě nebaví
 3. Spím

**Comment by iff11** [comment]
o vikendu se na to vrhnu, az bude zase snezit ...
