### ISSUE TITLE
Neprihlaseny nemap prava na zadavani wormu

### ISSUE THREAD

**Issue by MichalBryxi** [MichalBryxi/bludistak#48]
Neprihlaseny uzivatel nesmi videt: /worms/new

http://stackoverflow.com/questions/15993993/restricting-users-to-create-new-article-in-blog-gives-undefined-method-is-adm

**Comment by iff11** [comment]
application controler si nadefinuju funkci ktera nekam presmerovavam checkovat na current user
a v jednotlivych controleru ji volam kdyz tam chci mit usera s vyjimkou v pravech

**Comment by iff11** [comment]
login pridat do config.routes.rb
