### ISSUE TITLE
Obrázek projektu

### ISSUE THREAD

**Issue by MichalBryxi** [MichalBryxi/bludistak#58]
- Přidat sloupeček `image_url` typu `string` do tabulky projektů (migrace)
- Zařídit zobrazení `image_url` jako obrázku v detailu projektu
- Zařídit možnost editace `image_url` v editaci projektu

**Comment by MichalBryxi** [comment]
Pozn: Nebudeme nikam uploadovat fyzické obrázky. Jen si uložíme URL a to URL pak použijem na zobrazení obrázku.

**Comment by iff11** [comment]
tohle uz by melo byt hotove

**Comment by MichalBryxi** [comment]
ok
